version: '3'

services:
  php_test_server:
    build: ./dockerfiles/nginx
    ports:
      - "8090:80"
    volumes:
      - ./src:/var/www/
      - ./configs/site.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php_test
  php_test:
    build: ./dockerfiles/php
    volumes:
      - ./src:/var/www/

